ReportingKnockout/Controllers/ReactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ReportingKnockout.Controllers
{
    public class ReactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReportingKnockout/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReportingKnockout.Controllers
{
    public class ReportingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetEmployeeColumns()
        {
            return Json(new string[] { "First Name", "Last Name", "Address1", "Username", "Email", "Telephone",  });
        }

        public IActionResult GetDataCodeColumns()
        {
            return Json(new string[] { "Code", "Description", "Payment or Deduction"});
        }

        public IActionResult GetAbsenseColumns()
        {
            return Json(new string[] { "Duration", "Cost" });
        }

        public IActionResult Submit(string columns)
        {
            return Json(columns);
        }
    }
}

ReportingKnockout/Views/React/Index.cshtml
<div class="container" id="root">

</div>

@section Scripts {
    <script src="~/dist/reactTest.js"></script>
}

ReportingKnockout/Views/Reporting/Index.cshtml
<div class="container" style="display: none;" data-bind="visible: true">

    <div id="employeeColumns">

        <h1>Reporting <span data-bind="text: selectedIndex"></span></h1>

        <div class="col-md-1">
            <button class="btn btn-block btn-default" data-bind="click: previous, disable: selectedIndex() <= 0">Prev</button>
        </div>

        <div class="col-md-10">
            <div class="well">

                <h2 data-bind="text: title"></h2>

                <!-- ko if: selectedIndex() < vmArray().length -->
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">

                        <div class="col-md-5">
                            <div class="list-group" data-bind="foreach: vmArray()[selectedIndex()].columns">
                                <button type="button" class="list-group-item" data-bind="text: $data, click: function(){$parent.vmArray()[$parent.selectedIndex()].addToSelectedColumns($data)}"></button>
                            </div>
                        </div>

                        <div class="col-md-1">
                            <h1>
                                <i class="fa fa-hand-o-right" aria-hidden="true"></i>
                            </h1>
                        </div>

                        <div class="col-md-5">
                            <div class="list-group" data-bind="foreach: vmArray()[selectedIndex()].selectedColumns">
                                <button type="button" class="list-group-item" data-bind="text: $data, click: function(){$parent.vmArray()[$parent.selectedIndex()].removeFromSelectedColumns($data)}"></button>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /ko -->

                <!-- ko if: selectedIndex() >= vmArray().length -->
                <div class="row">
                    <div class="col-md-12">
                        <div data-bind="foreach: {data : vmArray(), as : 'item'}">
                            <div class="col-md-5">
                                <h4 data-bind="text: item.name"></h4>
                                <div class="list-group" data-bind="foreach: {data: selectedColumns, as : 'columns'}">
                                    <button type="button" class="list-group-item" data-bind="text: columns"></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1 col-md-offset-10">
                            <button id="submit" class="btn btn-success" data-bind="click: submit">Submit</button>
                        </div>
                    </div>
                </div>
                <!-- /ko -->
            </div>
        </div>

        <div class="col-md-1">
            <button class="btn btn-block btn-info" data-bind="click: next, disable: selectedIndex() >= vmArray().length">Next</button>
        </div>

    </div>

</div>

<!--div id="debug">
    <hr />
    <h2>Debug</h2>
    <div data-bind="text: ko.toJSON($data)"></div>
</div-->



@section Scripts {
    <script src="~/dist/reporting.js"></script>
    <script>
        console.log(window);
        console.log($);
        console.log(jQuery);
    </script>
}

ReportingKnockout/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Reporting</title>

    <link rel="stylesheet" href="~/dist/vendor.css" />
    <link rel="stylesheet" href="~/dist/site.css"/>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">FrontEnd</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Reporting" asp-action="Index">Knockout</a></li>
                    <li><a asp-controller="React" asp-action="Index">React</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div>
        @RenderBody()
    </div>

    <script src="~/dist/vendor.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>